version: '3'
services: 
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports: 
      - '3050:80'  
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes: 
      #leave this folder as is 
      - /app/node_modules 
      #redirect to inside the project folder
      - ./server:/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres #default
      - PGHOST=postgres #name of service
      - PGDATABASE=postgres #default
      - PGPASSWORD=postgres_password #default
      - PGPORT=5432 #default
  client:
    build:
      dockerfile: Dockerfile.dev 
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app